development:
  adapter: postgresql
  database: mo_ads_development
  encoding: utf8
  pool: 5
  timeout: 5000
  username: umedia
  password: 123
  host: 127.0.0.1

production:
  adapter: postgresql
  database: mo_ads_production
  encoding: utf8
  pool: 5
  timeout: 5000
  username: umedia
  password: 123
  host: 127.0.0.1
